INSERT INTO person VALUES ("firstName":"John", "lastName":"Boyd", "address":"1509 Culver St", "city":"Culver", "zip":"97451", "phone":"841-874-6512", "email":"jaboyd@email.com");
INSERT INTO person VALUES ("firstName":"Jacob", "lastName":"Boyd", "address":"1509 Culver St", "city":"Culver", "zip":"97451", "phone":"841-874-6513", "email":"drk@email.com");
INSERT INTO person VALUES ("firstName":"Tenley", "lastName":"Boyd", "address":"1509 Culver St", "city":"Culver", "zip":"97451", "phone":"841-874-6512", "email":"tenz@email.com");
INSERT INTO person VALUES ("firstName":"Roger", "lastName":"Boyd", "address":"1509 Culver St", "city":"Culver", "zip":"97451", "phone":"841-874-6512", "email":"jaboyd@email.com");
INSERT INTO person VALUES ("firstName":"Felicia", "lastName":"Boyd", "address":"1509 Culver St", "city":"Culver", "zip":"97451", "phone":"841-874-6544", "email":"jaboyd@email.com");
INSERT INTO person VALUES ("firstName":"Jonanathan", "lastName":"Marrack", "address":"29 15th St", "city":"Culver", "zip":"97451", "phone":"841-874-6513", "email":"drk@email.com");
INSERT INTO person VALUES ("firstName":"Tessa", "lastName":"Carman", "address":"834 Binoc Ave", "city":"Culver", "zip":"97451", "phone":"841-874-6512", "email":"tenz@email.com");
INSERT INTO person VALUES ("firstName":"Peter", "lastName":"Duncan", "address":"644 Gershwin Cir", "city":"Culver", "zip":"97451", "phone":"841-874-6512", "email":"jaboyd@email.com");
INSERT INTO person VALUES ("firstName":"Foster", "lastName":"Shepard", "address":"748 Townings Dr", "city":"Culver", "zip":"97451", "phone":"841-874-6544", "email":"jaboyd@email.com");
INSERT INTO person VALUES ("firstName":"Tony", "lastName":"Cooper", "address":"112 Steppes Pl", "city":"Culver", "zip":"97451", "phone":"841-874-6874", "email":"tcoop@ymail.com");
INSERT INTO person VALUES ("firstName":"Lily", "lastName":"Cooper", "address":"489 Manchester St", "city":"Culver", "zip":"97451", "phone":"841-874-9845", "email":"lily@email.com");
INSERT INTO person VALUES ("firstName":"Sophia", "lastName":"Zemicks", "address":"892 Downing Ct", "city":"Culver", "zip":"97451", "phone":"841-874-7878", "email":"soph@email.com");
INSERT INTO person VALUES ("firstName":"Warren", "lastName":"Zemicks", "address":"892 Downing Ct", "city":"Culver", "zip":"97451", "phone":"841-874-7512", "email":"ward@email.com");
INSERT INTO person VALUES ("firstName":"Zach", "lastName":"Zemicks", "address":"892 Downing Ct", "city":"Culver", "zip":"97451", "phone":"841-874-7512", "email":"zarc@email.com");
INSERT INTO person VALUES ("firstName":"Reginold", "lastName":"Walker", "address":"908 73rd St", "city":"Culver", "zip":"97451", "phone":"841-874-8547", "email":"reg@email.com");
INSERT INTO person VALUES ("firstName":"Jamie", "lastName":"Peters", "address":"908 73rd St", "city":"Culver", "zip":"97451", "phone":"841-874-7462", "email":"jpeter@email.com");
INSERT INTO person VALUES ("firstName":"Ron", "lastName":"Peters", "address":"112 Steppes Pl", "city":"Culver", "zip":"97451", "phone":"841-874-8888", "email":"jpeter@email.com");
INSERT INTO person VALUES ("firstName":"Allison", "lastName":"Boyd", "address":"112 Steppes Pl", "city":"Culver", "zip":"97451", "phone":"841-874-9888", "email":"aly@imail.com");
INSERT INTO person VALUES ("firstName":"Brian", "lastName":"Stelzer", "address":"947 E. Rose Dr", "city":"Culver", "zip":"97451", "phone":"841-874-7784", "email":"bstel@email.com");
INSERT INTO person VALUES ("firstName":"Shawna", "lastName":"Stelzer", "address":"947 E. Rose Dr", "city":"Culver", "zip":"97451", "phone":"841-874-7784", "email":"ssanw@email.com");
INSERT INTO person VALUES ("firstName":"Kendrik", "lastName":"Stelzer", "address":"947 E. Rose Dr", "city":"Culver", "zip":"97451", "phone":"841-874-7784", "email":"bstel@email.com");
INSERT INTO person VALUES ("firstName":"Clive", "lastName":"Ferguson", "address":"748 Townings Dr", "city":"Culver", "zip":"97451", "phone":"841-874-6741", "email":"clivfd@ymail.com");
INSERT INTO person VALUES ("firstName":"Eric", "lastName":"Cadigan", "address":"951 LoneTree Rd", "city":"Culver", "zip":"97451", "phone":"841-874-7458", "email":"gramps@email.com");

INSERT INTO firestation VALUES ("address":"1509 Culver St", "station":"3");
INSERT INTO firestation VALUES ("address":"29 15th St", "station":"2");
INSERT INTO firestation VALUES ("address":"834 Binoc Ave", "station":"3");
INSERT INTO firestation VALUES ("address":"644 Gershwin Cir", "station":"1");
INSERT INTO firestation VALUES ("address":"748 Townings Dr", "station":"3");